POST http://localhost:4500/user/register
Content-Type: application/json

{
    "firstname": "Anthony",
    "lastname":"Kigotho",
    "email":"anthony.kigotho@thejitu.com",
    "cohort": 17,
    "password":"pass1234"
}
